include: package:flutter_lints/flutter.yaml

linter:
  # A list of all available lints and their documentation is published at https://dart.dev/lints.
  rules:
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
